# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.9
minecraft_version_range=[1.21.9,1.22)
neo_version=21.9.2-beta
neo_version_range=[21.9.1-beta,)
loader_version_range=[4,)
mod_dev_gradle=2.0.110

## Parchment
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14

## Mod Properties
mod_version=7.3.0
edivadlib_id=7057090
edivadlib_version_range=[3.3.1,)

# Dependencies
jei_version=25.0.0.2
