modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GNU AGPLv3"
issueTrackerURL = "https://github.com/Edivad99/SolarGeneration/issues"

[[mods]]
  modId = "solargeneration"
  version = "${mod_version}"
  displayName = "SolarGeneration"
  updateJSONURL = "https://api.modrinth.com/updates/solargeneration/forge_updates.json?neoforge=include"
  modUrl = "https://www.curseforge.com/minecraft/mc-mods/solargeneration"
  authors = "Edivad99"
  description = "A way to generate FE from the sun"

[[dependencies.solargeneration]]
  modId = "neoforge"
  type = "required"
  versionRange = "${neo_version_range}"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.solargeneration]]
  modId = "minecraft"
  type = "required"
  versionRange = "${minecraft_version_range}"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.solargeneration]]
  modId = "edivadlib"
  type = "required"
  versionRange = "${edivadlib_version_range}"
  ordering = "NONE"
  side = "BOTH"
