modLoader="javafml"
loaderVersion="[47,)"
license="GNU AGPLv3"

[[mods]]
modId="solargeneration"
version="${mod_version}"
displayName="SolarGeneration"
updateJSONURL = "https://api.modrinth.com/updates/solargeneration/forge_updates.json"
issueTrackerURL="https://github.com/Edivad99/SolarGeneration/issues"
modUrl="https://www.curseforge.com/minecraft/mc-mods/solargeneration"
authors="Edivad99"
description="A way to generate FE from the sun"

[[dependencies.solargeneration]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solargeneration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solargeneration]]
    modId="edivadlib"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="NONE"
    side="BOTH"
