modLoader="javafml"
loaderVersion="[47,)"
license="GNU AGPLv3"

[[mods]]
modId="solargeneration"
version="${file.jarVersion}"
displayName="Solar Generation"
updateJSONURL="https://raw.githubusercontent.com/Edivad99/mod-version-controll/master/solargeneration_update.json"
issueTrackerURL="https://github.com/Edivad99/SolarGeneration/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/solargeneration"
authors="edivad"
description="A way to generate FE from the sun"

[[dependencies.solargeneration]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solargeneration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.solargeneration]]
    modId="edivadlib"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="NONE"
    side="BOTH"
