name: 'SolarGeneration CI'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build
        run: ./gradlew build --max-workers 1
